language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install flake8
  - pip install autopep8
  - pip3 install git+git://github.com/python/mypy.git


# command to run tests
script:
  - flake8 python_lab.py
  - python3 -m doctest python_lab.py
  - flake8 --max-complexity=2

#- autopep8 python_lab.py
